
import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function POST(req: Request) {
    try {
        const body = await req.json();
        const { installPath, navbarColor, headingColor, quicklinkColor, hoverColor, reset } = body;

        if (!installPath) {
            return NextResponse.json({ error: 'Installation path is required' }, { status: 400 });
        }

        const cssFile = path.join(installPath, 'ui', 'css', 'ui-custom.css');
        const cssDir = path.dirname(cssFile);

        // Ensure directory exists
        if (!fs.existsSync(cssDir)) {
            return NextResponse.json({ error: 'Invalid IdentityIQ path: ui/css directory not found' }, { status: 400 });
        }

        // Read existing CSS or start empty
        let content = '';
        if (fs.existsSync(cssFile)) {
            content = fs.readFileSync(cssFile, 'utf-8');
        }

        // Define our custom block
        // Define our custom block
        const startMarker = '/* START_SAILSETU_CUSTOM */';
        const endMarker = '/* END_SAILSETU_CUSTOM */';

        // Escape special regex characters in the markers (specifically *)
        const escapeRegex = (string: string) => string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const regex = new RegExp(`${escapeRegex(startMarker)}[\\s\\S]*?${escapeRegex(endMarker)}`, 'g');

        if (reset) {
            // Remove the block if custom CSS exists
            if (regex.test(content)) {
                const newContent = content.replace(regex, '').trim();
                fs.writeFileSync(cssFile, newContent, 'utf-8');
                return NextResponse.json({ success: true, message: 'Successfully restored default CSS.' });
            } else {
                return NextResponse.json({ success: true, message: 'No custom CSS found to reset.' });
            }
        }

        const customRules = `
${startMarker}
/* Auto-generated by SailSetu Product Customizer */

/* 1. NAVBAR - User Selection: ${navbarColor} */
/* Match Navbar Background & Border */
.navbar-default, 
.navbar,
.header.bg-primary,
.header.navbar,
nav.header { 
    background-color: ${navbarColor} !important; 
    border-color: ${navbarColor} !important; 
    background-image: none !important;
}

/* Navbar Text - Force White */
.navbar-default .navbar-nav > li > a,
.navbar .navbar-nav > li > a,
.header .navbar-nav > li > a,
.navbar-brand {
    color: #ffffff !important;
}

/* 2. SIDEBAR - Force Match Navbar (As Requested) */
#quicklinkPanel,
.quicklink-panel,
.bg-primary,
.bg-primary.lt,
/* Inner Sidebar Panels */
#quicklinkPanel .panel-heading,
#quicklinkPanel .panel-body,
.quicklink-panel .panel-heading,
.quicklink-panel .panel-body,
/* Specific IDs seen in screenshot */
#quicklinkCategoryTasks .panel-heading,
#quicklinkCategoryTasks .panel-body,
#quicklinkCategoryManage .panel-heading,
#quicklinkCategoryManage .panel-body  {
    background-color: ${navbarColor} !important;
    border-color: ${navbarColor} !important;
    background-image: none !important;
}

/* Sidebar Text - Force White */
#quicklinkPanel a,
#quicklinkPanel span,
#quicklinkPanel .panel-title,
#quicklinkPanel i,
#quicklinkPanel .fa,
.quicklink-panel a,
.quicklink-panel span,
.quicklink-panel .text-info,
.quicklink-panel .text-primary,
.quicklink-panel i,
.quicklink-panel .fa {
    color: #ffffff !important;
}

/* 3. HEADINGS - User Selection: ${headingColor} */
.widget-title, 
.panel-title, 
.card-title,
.panel-heading,
.card-header,
h1, h2, h3, h4, h5, h6,
.text-info,
.text-primary,
.panel-heading .text-info,
.panel-heading .text-primary,
/* ExtJS Tab Headers - User Request: ACTIVE ONLY */
.x-tab-strip-active .x-tab-right,
.x-tab-strip-active .x-tab-inner,
.x-tab-active .x-tab-inner,
.x-tab-active .x-btn-inner,
/* Info Text / Section Headers (Keep these global) */
.spContentTitle,
legend,
.section-header,
h4 { 
    color: ${headingColor} !important; 
}

/* Save / Primary Action Buttons - User Request: Match Navbar Color */
.primaryBtn,
input.primaryBtn,
button.primaryBtn {
    background-color: ${navbarColor} !important;
    background-image: none !important;
    color: #ffffff !important;
    border-color: ${navbarColor} !important;
}

/* Cancel / Secondary Action Buttons - User Request: Text Color Match Navbar */
.secondaryBtn,
input.secondaryBtn,
button.secondaryBtn {
    color: ${navbarColor} !important;
    background: #ffffff !important; /* Ensure readable contrast if custom BG rules existed */
    border-color: #cccccc !important;
}

/* 4. BUTTONS & QUICKLINKS - User Selection: ${quicklinkColor} */
/* Replace standard Bootstrap Blue and SailPoint Buttons */
.btn-primary,
.btn-info,
.btn-default:hover {
    background-color: ${quicklinkColor} !important;
    border-color: ${quicklinkColor} !important;
    color: #ffffff !important;
}

/* ExtJS Buttons / Toggles (Direct/Effective, Advanced Search) - REVERTED */
/* Pressed/Active Buttons -> Custom BG, White Text */
html body .x-btn-default-small.x-btn-pressed,
html body .x-btn-default-toolbar-small-pressed,
html body .x-btn-pressed {
    background-color: ${quicklinkColor} !important;
    border-color: ${quicklinkColor} !important;
    background-image: none !important;
}
html body .x-btn-pressed .x-btn-inner,
html body .x-btn-over .x-btn-inner {
    color: #ffffff !important;
}

/* Unpressed / Default Buttons (Standard state) -> Custom Text Color */
html body .x-btn-inner,
html body .x-btn-default-small .x-btn-inner,
html body .x-btn-default-toolbar-small .x-btn-inner {
    color: ${quicklinkColor} !important;
}

/* Dropdown / Action Buttons (e.g. "New Task") - User Request */
.menuBtnClass,
.menuBtnClass.x-btn-default-small {
    background-color: ${navbarColor} !important;
    border-color: ${navbarColor} !important;
    color: #ffffff !important;
    background-image: none !important;
}
html body .menuBtnClass .x-btn-inner,
html body .menuBtnClass *,
html body .menuBtnClass .x-btn-icon-el {
     color: #ffffff !important;
}

/* ExtJS Dropdown Menu Items (Hover State) */
html body .x-menu-item-active,
html body .x-menu-item-active .x-menu-item-text,
html body .x-menu-item-active .x-menu-item-link {
    background-color: ${hoverColor} !important;
    color: #ffffff !important;
    background-image: none !important;
    border-color: ${hoverColor} !important;
}
html body .x-menu-item-active * {
    color: #ffffff !important;
}

/* Dashboard Cards / Quicklinks - TEXT COLOR ONLY (User Request) */
/* Force Background to White */
html body .quickLink-ct .quickLink,
html body .quicklink-card-link .panel,
html body .task-card,
html body .panel.task-card,
html body .quickLink > div {
     background-color: #ffffff !important;
     background: #ffffff !important;
     border-color: #dddddd !important; 
}

/* Apply Custom Color to Text & Icons */
html body .quickLink-ct .quickLink h1,
html body .quickLink-ct .quickLink h2,
html body .quickLink-ct .quickLink h3,
html body .quickLink-ct .quickLink span,
html body .quickLink-ct .quickLink i,
html body .quickLink-ct .quickLink a,
html body .task-card .card-title,
html body .task-card .card-arrow-icon,
html body .task-card i,
html body .quicklink-card-link i,
html body .quicklink-card-link .card-title,
html body .quicklink-card-link .card-text {
    color: ${quicklinkColor} !important;
}

/* Ensure other text remains standard if not targeted */
html body .task-card .text-muted {
    color: #777777 !important;
}

/* Active Tabs / States */
.nav-tabs > li.active > a, 
.nav-tabs > li.active > a:hover, 
.nav-tabs > li.active > a:focus {
    color: ${quicklinkColor} !important;
    border-bottom: 2px solid ${quicklinkColor} !important;
}

/* 5. HOVER STATES - User Selection: ${hoverColor} */
/* Links Hover */
a:hover, a:focus,
.navbar-nav > li > a:hover {
    color: ${hoverColor} !important;
    text-decoration: none !important;
}

/* Button Hover - Only apply to primary/info buttons to avoid breaking everything */
.btn-primary:hover,
.btn-primary:focus,
.btn-info:hover {
    background-color: ${hoverColor} !important;
    border-color: ${hoverColor} !important;
}

/* Sidebar/Nav Item Hover */
.nav > li > a:hover,
.nav > li > a:focus,
/* Navbar Active/Open Dropdown - Fix for "Click items didn't inherit hover color" */
.navbar-nav > li.open > a,
.navbar-nav > li.open > a:hover,
.navbar-nav > li.open > a:focus,
/* Dropdown Menu Items Hover - Fix for submenu blue highlight */
.dropdown-menu > li > a:hover,
.dropdown-menu > li > a:focus,
/* Sidebar Panel Hover - Fix for "sidebar items not working" */
#quicklinkPanel .panel-heading:hover,
#quicklinkPanel .panel-heading:focus,
.quicklink-panel .panel-heading:hover,
#quicklinkCategoryTasks .panel-heading:hover,
#quicklinkCategoryManage .panel-heading:hover,
#quicklinkCategoryAccess .panel-heading:hover,
#quicklinkCategoryIdentity .panel-heading:hover {
    background-color: ${hoverColor} !important;
     color: #ffffff !important;
}
${endMarker}
`;

        // Replace or Append

        let newContent = content;
        if (regex.test(content)) {
            newContent = content.replace(regex, customRules.trim());
        } else {
            newContent = content + '\n\n' + customRules.trim();
        }

        fs.writeFileSync(cssFile, newContent, 'utf-8');

        return NextResponse.json({ success: true, message: 'Successfully updated ui-custom.css' });

    } catch (e) {
        console.error(e);
        return NextResponse.json({ error: 'Internal Server Error', details: String(e) }, { status: 500 });
    }
}
